### ISSUE TITLE
Precompilation support in Bundlex

### ISSUE THREAD

**Issue by Noarkhh** [membraneframework/membrane_core#604]
### User story:

As a Membrane user, I want the native libraries to be shipped with Elixir packages, so I don’t have to install them manually and make them discoverable by Bundlex.

### AC:

- A Bundlex user can add a precompiled library file for each platform

- If a platform matches, the precompiled version is used, otherwise, Bundlex tries to compile the library

- Precompile some Membrane packages, FFmpeg and libsrtp for example, and use them to test the new feature.

### Subtasks:
- [x] membraneframework/membrane_core/issues/605
- [x] membraneframework/membrane_core/issues/606
- [x] membraneframework/membrane_core/issues/607
- [x] membraneframework/membrane_core/issues/603
- [x] membraneframework/membrane_core/issues/608
- [x] membraneframework/membrane_core/issues/609
- [x] membraneframework/membrane_core/issues/636
