### ISSUE TITLE
Support for Nerves

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_core#630]
#### User story:
As a Nerves user, I'd like to use Membrane to stream from an IOT device to:
- a media server
- a browser, directly.

#### AC:
- Running pure-Elixir Membrane pipelines on Nerves
- [Bundlex] Cross-compiling native parts for Nerves
- Capturing & encoding stream from the camera (possibly without passing unencoded stream to the pipeline)
- A real-life example of streaming from Nerves to a media server and to a browser

#### Subtasks:
- [x] membraneframework/membrane_core#675
- [x] membraneframework/membrane_core#676
- [x] membraneframework/membrane_core#677
